In [3]:

a='{"objects":[{"bbox":[123,662,2308,2804],"label":0,"prob":0.595},{"bbox":[237,895,1437,2738],"label":0,"prob":0.5545},{"bbox":[158,534,2186,1050],"label":0,"prob":0.3244},{"bbox":[310,1512,2151,2858],"label":0,"prob":0.1664},{"bbox":[306,783,2188,1851],"label":0,"prob":0.1482},{"bbox":[291,1282,1027,2758],"label":0,"prob":0.0825},{"bbox":[253,2109,2213,2766],"label":0,"prob":0.0612},{"bbox":[171,754,2193,1311],"label":0,"prob":0.0458},{"bbox":[482,901,2222,1103],"label":0,"prob":0.0445},{"bbox":[272,1930,1299,2742],"label":0,"prob":0.0388},{"bbox":[253,504,1042,1097],"label":0,"prob":0.0327},{"bbox":[1342,803,2279,2831],"label":0,"prob":0.0269},{"bbox":[345,984,2283,1501],"label":0,"prob":0.0257},{"bbox":[508,1008,2287,1269],"label":0,"prob":0.0243},{"bbox":[189,2323,1443,2683],"label":0,"prob":0.0202},{"bbox":[236,576,1441,934],"label":0,"prob":0.0149},{"bbox":[1133,884,2284,1936],"label":0,"prob":0.0148},{"bbox":[481,572,680,952],"label":0,"prob":0.0133},{"bbox":[208,707,1881,973],"label":0,"prob":0.0118}]}'

In [4]:
a

'{"objects":[{"bbox":[123,662,2308,2804],"label":0,"prob":0.595},{"bbox":[237,895,1437,2738],"label":0,"prob":0.5545},{"bbox":[158,534,2186,1050],"label":0,"prob":0.3244},{"bbox":[310,1512,2151,2858],"label":0,"prob":0.1664},{"bbox":[306,783,2188,1851],"label":0,"prob":0.1482},{"bbox":[291,1282,1027,2758],"label":0,"prob":0.0825},{"bbox":[253,2109,2213,2766],"label":0,"prob":0.0612},{"bbox":[171,754,2193,1311],"label":0,"prob":0.0458},{"bbox":[482,901,2222,1103],"label":0,"prob":0.0445},{"bbox":[272,1930,1299,2742],"label":0,"prob":0.0388},{"bbox":[253,504,1042,1097],"label":0,"prob":0.0327},{"bbox":[1342,803,2279,2831],"label":0,"prob":0.0269},{"bbox":[345,984,2283,1501],"label":0,"prob":0.0257},{"bbox":[508,1008,2287,1269],"label":0,"prob":0.0243},{"bbox":[189,2323,1443,2683],"label":0,"prob":0.0202},{"bbox":[236,576,1441,934],"label":0,"prob":0.0149},{"bbox":[1133,884,2284,1936],"label":0,"prob":0.0148},{"bbox":[481,572,680,952],"label":0,"prob":0.0133},{"bbox":[208,707,1881,973],"l

In [14]:
import cv2
import numpy as np
imgg=cv2.imread(r'/mnt/d/djangoProjectImage/mysite/media/processImage/template3aa_2019-08-16_17-03-56/Auto-Color2354-29.jpg')

# Convert BGR to HSV
hsv = cv2.cvtColor(imgg, cv2.COLOR_BGR2HSV)

# define range of black color in HSV
lower_val = np.array([0,0,0])
upper_val = np.array([160,255,127])

# Threshold the HSV image to get only black colors
mask = cv2.inRange(hsv, lower_val, upper_val)

# invert mask to get black symbols on white background
mask_inv = cv2.bitwise_not(mask)


In [15]:
cv2.imwrite('/mnt/d/mask_inv.jpg',mask_inv)

True

In [17]:
import numpy as np
from PIL import Image

im = Image.open(r'/mnt/d/djangoProjectImage/mysite/media/processImage/template3aa_2019-08-16_17-03-56/Auto-Color2354-29.jpg')
im = im.convert('RGBA')
data = np.array(im)
# just use the rgb values for comparison
rgb = data[:,:,:3]
color = [246, 213, 139]   # Original value
black = [0,0,0, 255]
white = [255,255,255,255]
mask = np.all(rgb == color, axis = -1)
# change all pixels that match color to white
data[mask] = white

# change all pixels that don't match color to black
##data[np.logical_not(mask)] = black
new_im = Image.fromarray(data)
new_im.save('new_file.tif')

In [5]:
from __future__ import print_function
import binascii
import struct
from PIL import Image
import numpy as np
import scipy
import scipy.misc
import scipy.cluster
from IPython.display import display
NUM_CLUSTERS = 5

print('reading image')
im = Image.open(r'/mnt/d/djangoProjectImage/mysite/media/processImage/template3aa_2019-08-16_17-03-56/Auto-Color2354-29.jpg')


#im = Image.open('image.jpg')
im = im.resize((150, 150))      # optional, to reduce time
ar = np.asarray(im)
shape = ar.shape
ar = ar.reshape(scipy.product(shape[:2]), shape[2]).astype(float)

print('finding clusters')
codes, dist = scipy.cluster.vq.kmeans(ar, NUM_CLUSTERS)
print('cluster centres:\n', codes)

vecs, dist = scipy.cluster.vq.vq(ar, codes)         # assign codes
counts, bins = scipy.histogram(vecs, len(codes))    # count occurrences

index_max = scipy.argmax(counts)                    # find most frequent
peak = codes[index_max]
colour = binascii.hexlify(bytearray(int(c) for c in peak)).decode('ascii')
print('most frequent is %s (#%s)' % (peak, colour))
#Image.fromarray(im)

reading image
finding clusters
cluster centres:
 [[148.87068966 150.96264368 165.64655172]
 [230.88888889 231.64509169 236.60517799]
 [ 39.50526316  39.33684211  40.91929825]
 [254.55162369 254.58763133 254.67898758]]
most frequent is [254.55162369 254.58763133 254.67898758] (#fefefe)


In [20]:
im = Image.open(r'/mnt/d/djangoProjectImage/mysite/media/processImage/template3aa_2019-08-16_17-03-56/Auto-Color2354-29.jpg')

im.getcolors()

In [21]:
!pip install colorthief

In [3]:
from colorthief import ColorThief
color_thief = ColorThief(r'/mnt/d/djangoProjectImage/mysite/media/processImage/template3aa_2019-08-16_17-03-56/Auto-Color2354-29.jpg')
# get the dominant color
dominant_color = color_thief.get_color(quality=1)

In [4]:
dominant_color

(237, 237, 241)